---
# This empty list gets appended to by every incident tasks/main.yaml file
documentation_json_file: "/tmp/sre-bench-docs.json"
all_incidents: [] # global list to which all or selected incidents get appended to at runtime
selected_incidents: [1, 3, 23, 26, 27, 37, 102] # when left blank all incidents are selected
