---
- import_tasks: enable_targeted_load.yaml
- import_tasks: install_chaos_mesh.yaml
- import_tasks: run_native.yaml
- import_tasks: run_chaos_network_delay.yaml
- import_tasks: run_chaos_network_partition.yaml
- import_tasks: run_chaos_pod_chaos.yaml
- import_tasks: run_chaos_memory_stress.yaml
- import_tasks: run_scale_replicas.yaml
- import_tasks: run_misconfigure_port.yaml
- import_tasks: run_assign_remove_nonexistent_node.yaml
- import_tasks: run_valkey_auth_disruption.yaml
- import_tasks: register_fault_injection_time.yaml
- import_tasks: run_chaos_http_abort.yaml
- import_tasks: run_unsupported_image.yaml
- import_tasks: run_chaos_request_body_tamper.yaml
- import_tasks: run_chaos_cpu_stress.yaml
- import_tasks: enable_namespace_memory_limit.yaml
- import_tasks: run_chaos_jvm_return.yaml
- import_tasks: run_chaos_jvm_heap_stress.yaml
- import_tasks: uninstall_chaos_mesh.yaml
- import_tasks: run_bin_misusage.yaml
- import_tasks: run_missing_storageclass.yaml
- import_tasks: elasticsearch_password.yaml
- import_tasks: run_unsupported_image.yaml
- import_tasks: run_storage_user_unregistered.yaml
