---
- name: Get the Ingress URL
  ansible.builtin.shell: "KUBECONFIG={{ kubeconfig }} kubectl get ingress prometheus -n {{ prometheus_namespace_project_name }} -o json"
  register: observability_stack_ingress
  retries: 5
  delay: 60
  until: (observability_stack_ingress.stdout | length) > 0
  ignore_errors: yes

- name: Extract the Ingress hostname information
  set_fact:
    ingress_hostname: "{{ observability_stack_ingress.stdout | from_json | json_query('status.loadBalancer.ingress[0].hostname') }}"
  when: observability_stack_ingress.stdout | trim != ''

- name: Set the Prometheus URL
  set_fact:
    prometheus_url: "http://{{ ingress_hostname }}/prometheus"
  when: ingress_hostname is defined and ingress_hostname | trim != ''

- name: Set the Jaeger URL
  set_fact:
    jaeger_url: "http://{{ ingress_hostname }}/jaeger"
  when: ingress_hostname is defined and ingress_hostname | trim != ''
