---
- name: Deploy OpenTelemetry Operator
  kubernetes.core.helm:
    name: "{{ opentelemetry_operator_installation_name }}"
    kubeconfig_path: "{{ kubeconfig }}"
    chart_ref: open-telemetry/opentelemetry-operator
    chart_version: "{{ opentelemetry_operator_chart_version }}"
    release_namespace: "{{ opentelemetry_operator_namespace_project_name }}"
    release_state: present
    create_namespace: true
    wait: true
    values:
      manager:
        collectorImage:
          repository: otel/opentelemetry-collector-k8s
      admissionWebhooks:
        certManager:
          enabled: false
        autoGenerateCert:
          enabled: true

- name: Create a namespace for OpenTelemetry Collectors
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    name: "{{ opentelemetry_operator_collectors_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Create a service account for OpenTelemetry Collector (Kubernetes Events)
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    name: "{{ opentelemetry_operator_collector_kubernetes_events_name }}-collector"
    namespace: "{{ opentelemetry_operator_collectors_namespace }}"
    api_version: v1
    kind: ServiceAccount
    state: present

- name: Create a cluster role for OpenTelemetry Collector (Kubernetes Events)
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    resource_definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        name: "{{ opentelemetry_operator_collector_kubernetes_events_name }}-collector"
      rules:
        - apiGroups:
            - events.k8s.io
          resources:
            - events
          verbs:
            - watch
            - list

- name: Create a cluster role binding for OpenTelemetry Collector (Kubernetes Events)
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    resource_definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: "{{ opentelemetry_operator_collector_kubernetes_events_name }}-collector"
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: "{{ opentelemetry_operator_collector_kubernetes_events_name }}-collector"
      subjects:
        - kind: ServiceAccount
          name: "{{ opentelemetry_operator_collector_kubernetes_events_name }}-collector"
          namespace: "{{ opentelemetry_operator_collectors_namespace }}"

- name: Deploy OpenTelemetry Collector (Kubernetes Events)
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    resource_definition:
      apiVersion: opentelemetry.io/v1beta1
      kind: OpenTelemetryCollector
      metadata:
        name: "{{ opentelemetry_operator_collector_kubernetes_events_name }}"
        namespace: "{{ opentelemetry_operator_collectors_namespace }}"
      spec:
        image: otel/opentelemetry-collector-contrib:0.123.0
        serviceAccount: "{{ opentelemetry_operator_collector_kubernetes_events_name }}-collector"
        config:
          exporters:
            debug: {}
            clickhouse:
              username: "{{ clickhouse_user }}"
              password: "{{ clickhouse_password }}"
              endpoint: tcp://{{ clickhouse_installation_name }}-clickhouse.{{ clickhouse_namespace_project_name }}.svc.cluster.local:9000
              logs_table_name: otel_k8s_events_logs
          receivers:
            k8sobjects:
              objects:
                - exclude_watch_type:
                    - DELETED
                  group: events.k8s.io
                  mode: watch
                  name: events
            otlp:
              protocols:
                grpc:
                  endpoint: 0.0.0.0:4317
                http:
                  endpoint: 0.0.0.0:4318
          service:
            pipelines:
              logs:
                receivers:
                  - otlp
                  - k8sobjects
                exporters:
                  - debug
                  - clickhouse

- name: Deploy OpenTelemetry Collector (Jaeger)
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    resource_definition:
      apiVersion: opentelemetry.io/v1beta1
      kind: OpenTelemetryCollector
      metadata:
        name: "{{ opentelemetry_operator_collector_jaeger_name }}"
        namespace: "{{ opentelemetry_operator_collectors_namespace }}"
      spec:
        image: jaegertracing/jaeger:2.5.0
        ports:
        - name: jaeger
          port: 16686
        config: "{{ lookup('ansible.builtin.template', 'templates/otel-jaeger-config.j2') | from_yaml }}"


# NOTE: The rewrite annotation is not added to the following Ingress because
#       when rewriting the path, it adds the wrong Content-Type header to the
#       request. This cases the Jaeger UI to not work correctly.

- name: Deploy Ingress for OpenTelemetry Collector (Jaeger)
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig }}"
    resource_definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: jaeger
        namespace: "{{ opentelemetry_operator_collectors_namespace }}"
      spec:
        ingressClassName: nginx
        rules:
          - http:
              paths:
                - pathType: ImplementationSpecific
                  path: /jaeger
                  backend:
                    service:
                      name: "{{ opentelemetry_operator_collector_jaeger_name }}-collector"
                      port:
                        number: 16686

- name: Wait for Kubernetes Events Collector pods to be ready
  kubernetes.core.k8s_info:
    kubeconfig: "{{ kubeconfig }}"
    kind: Pod
    namespace: "{{ opentelemetry_operator_collectors_namespace }}"
    label_selectors:
      - "app.kubernetes.io/name=kubernetes-events-collector"
      - "app.kubernetes.io/instance=opentelemetry-collectors.kubernetes-events"
      - "app.kubernetes.io/managed-by=opentelemetry-operator"
    wait: yes
    wait_sleep: 30
    wait_timeout: 600
    wait_condition:
      type: Ready
      status: "True"

- name: Wait for Jaeger Collector pods to be ready
  kubernetes.core.k8s_info:
    kubeconfig: "{{ kubeconfig }}"
    kind: Pod
    namespace: "{{ opentelemetry_operator_collectors_namespace }}"
    label_selectors:
      - "app.kubernetes.io/name=jaeger-collector"
      - "app.kubernetes.io/instance=opentelemetry-collectors.jaeger"
      - "app.kubernetes.io/managed-by=opentelemetry-operator"
    wait: yes
    wait_sleep: 30
    wait_timeout: 600
    wait_condition:
      type: Ready
      status: "True"
