---
- name: Deploy Clickhouse Operator and Clickhouse
  kubernetes.core.helm:
    name: "{{ clickhouse_installation_name }}"
    kubeconfig_path: "{{ kubeconfig }}"
    chart_ref: altinity/clickhouse
    chart_version: "{{ clickhouse_chart_version }}"
    release_namespace: "{{ clickhouse_namespace_project_name }}"
    release_state: present
    create_namespace: true
    wait: true
    timeout: 10m0s
    values:
      clickhouse:
        defaultUser:
          allowExternalAccess: true

- name: Wait for Clickhouse install to complete
  kubernetes.core.k8s_info:
    api_version: clickhouse.altinity.com/v1
    kind: ClickHouseInstallation
    name: "{{ clickhouse_installation_name }}"
    namespace: "{{ clickhouse_namespace_project_name }}"
    kubeconfig: "{{ kubeconfig }}"
    wait: true
  register: clickhouse_installation_info
  until:
    - clickhouse_installation_info.resources[0].status.status is defined
    - clickhouse_installation_info.resources[0].status.status == 'Completed'
  retries: 4
  delay: 30

- name: Get Clickhouse credentials from secret
  kubernetes.core.k8s_info:
    kind: Secret
    name: clickhouse-credentials
    namespace: "{{ clickhouse_namespace_project_name }}"
    kubeconfig: "{{ kubeconfig }}"
    wait: true
  register: clickhouse_secrets_info

- name: Extract Clickhouse credentials from secret data
  ansible.builtin.set_fact:
    clickhouse_user: "{{ clickhouse_secrets_info.resources[0].data.user | b64decode }}"
    clickhouse_password: "{{ clickhouse_secrets_info.resources[0].data.password | b64decode }}"

- name: Deploy Ingress for Clickhouse
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig }}"
    resource_definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: clickhouse
        namespace: "{{ clickhouse_namespace_project_name }}"
        annotations:
          nginx.ingress.kubernetes.io/rewrite-target: /$2
      spec:
        ingressClassName: nginx
        rules:
          - http:
              paths:
                - pathType: ImplementationSpecific
                  path: /clickhouse(/|$)(.*)
                  backend:
                    service:
                      name: "{{ clickhouse_installation_name }}-clickhouse"
                      port:
                        number: 8123
