---
- name: Deploy Kubernetes Metric Server
  kubernetes.core.helm:
    name: "{{ metrics_server_installation_name }}"
    kubeconfig_path: "{{ kubeconfig }}"
    chart_ref: metrics-server/metrics-server
    chart_version: "{{ metrics_server_chart_version }}"
    release_namespace: "{{ metrics_server_namespace_project_name }}"
    release_state: present
    create_namespace: true
