---
scenario_domain: finops
sample_application: otel_astronomy_shop

is_install_chaos_mesh: false
target_namespace_name: "{{ otel_astronomy_app_namespace_project_name }}"
target_deployments:
  - accounting
  - ad
  - cart
  - checkout
  - currency
  - email
  - flagd
  - frauddetection
  - frontend
  - frontend-proxy
  - image-provider
  - kafka
  - otelcol
  - payment
  - product-catalog
  - quote
  - recommendation
  - shipping
  - valkey-cart

docs_incident_37:
  "id": 37
  "name": "Large cost variation"
  "platform": kubernetes
  "dsl_format": groups
  "description": "Services has scaled beyond budget due to high traffic"
  "application": "otel_astronomy_shop"
  "complexity": "Low"
  "inject_fault_unused": true
  "agent_operation_timeout_sec": 3000
  "bundle_ready_timeout_sec": 3000
  "fault": []

  alerts:
    - id: CPUSpend
      text: "Cost has increased more than 20 percent"
      group_id: otel-demo-namespace-1
      metadata:
        description: CPU spend increased by 20 percent
    - id: MemorySpend
      text: "Cost has increased more than 20 percent"
      group_id: otel-demo-namespace-1
      metadata:
        description: Memory spend increase
  groups:
    - id: otel-demo-namespace-1
      kind: Namespace
      name: otel-demo
      namespace: ""
      root_cause: true
  recommended_actions:
  - solution:
      id: "no_action"
      actions:
        - no changes is needed in application
        - update opencost alert to prevent false alerts
    # - time_to_clear_alert: 120s

  metrics:
  - type: "rate"
    value: "27.8"
  - type: "efficiency"
    value: "52"
